#!/bin/env bash

# Turns off all of my monitors, except the main one.

xrandr --output HDMI-0 --off --output DP-0 --off --output DP-1 --off --output DP-2 --off --output DP-3 --off --output DP-4 --primary --mode 1920x1080 --pos 0x0 --rate 200 --rotate normal --output DP-5 --off